spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/study?useSSL=false&serverTimezone=UTC
    username: root
    password: root
mybatis-plus:
  type-enums-package: xyz.redhawk.mybatisplus.enums
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
